version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: 18  # Specify the Node.js version you want
    ports:
      - "5001:5000"
      - "5002:5000"
      - "5003:5000"
    deploy:
      replicas: 3
